config/routes.rb
Rails.application.routes.draw do
  resources :stamps

  resources :tournaments

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'root#index'

  get 'root/index'

  mount API => '/'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    if user.has_role?('admin')
      can :read, :all
      can :access, :rails_admin
      can :dashboard
      if user.has_role?('superadmin')
        can :manage, :all
      else
        can :manage, [] # A
      end
    else
      can :read, [] # B
      can :create, [] # C
    end
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/stamp.rb
class Stamp < ActiveRecord::Base
  belongs_to :tournament

  scope :publishing, -> (time) { includes(:tournament).where("tournaments.started_at <= ? and tournaments.ended_at >= ? and tournaments.deleted = ?", time, time, false).where("stamps.deleted = ?", false).references(:tournament) }

  has_attached_file :photo, styles: {medium: "400x400>", thumb: "100x100>"}

  validates_attachment :photo, content_type: {content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]}

end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  has_many :stamps

  scope :publishing, -> (time) { where("started_at <= ? and ended_at >= ? and deleted = ?", time, time, false) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :roles

  def has_role?(name)
    self.roles.where(name: name).length > 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  end
end

app/controllers/stamps_controller.rb
class StampsController < ApplicationController
  before_action :set_stamp, only: [:show, :edit, :update, :destroy]

  # GET /stamps
  # GET /stamps.json
  def index
    @stamps = Stamp.all
  end

  # GET /stamps/1
  # GET /stamps/1.json
  def show
  end

  # GET /stamps/new
  def new
    @stamp = Stamp.new
  end

  # GET /stamps/1/edit
  def edit
  end

  # POST /stamps
  # POST /stamps.json
  def create
    @stamp = Stamp.new(stamp_params)

    respond_to do |format|
      if @stamp.save
        format.html { redirect_to @stamp, notice: 'Stamp was successfully created.' }
        format.json { render :show, status: :created, location: @stamp }
      else
        format.html { render :new }
        format.json { render json: @stamp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stamps/1
  # PATCH/PUT /stamps/1.json
  def update
    respond_to do |format|
      if @stamp.update(stamp_params)
        format.html { redirect_to @stamp, notice: 'Stamp was successfully updated.' }
        format.json { render :show, status: :ok, location: @stamp }
      else
        format.html { render :edit }
        format.json { render json: @stamp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stamps/1
  # DELETE /stamps/1.json
  def destroy
    @stamp.destroy
    respond_to do |format|
      format.html { redirect_to stamps_url, notice: 'Stamp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stamp
      @stamp = Stamp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stamp_params
      params.require(:stamp).permit(:tournament_id, :name, :beacon_minor, :latitude, :longitude, :deleted, :photo, :photo_file_name)
    end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: [:show, :edit, :update, :destroy]

  # GET /tournaments
  # GET /tournaments.json
  def index
    @tournaments = Tournament.all
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
  end

  # GET /tournaments/new
  def new
    @tournament = Tournament.new
  end

  # GET /tournaments/1/edit
  def edit
  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    @tournament = Tournament.new(tournament_params)

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to @tournament, notice: 'Tournament was successfully created.' }
        format.json { render :show, status: :created, location: @tournament }
      else
        format.html { render :new }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournaments/1
  # PATCH/PUT /tournaments/1.json
  def update
    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to @tournament, notice: 'Tournament was successfully updated.' }
        format.json { render :show, status: :ok, location: @tournament }
      else
        format.html { render :edit }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    @tournament.destroy
    respond_to do |format|
      format.html { redirect_to tournaments_url, notice: 'Tournament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tournament_params
      params.require(:tournament).permit(:name, :beacon_major, :started_at, :ended_at, :deleted)
    end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/stamps_helper.rb
module StampsHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Stampit
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if user_signed_in?
      %div= link_to 'Logout', destroy_user_session_path, method: :delete
    - else    
      %div= link_to 'Login', new_user_session_path
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/root/index.html.haml
%h1 Root#index
%p Find me in app/views/root/index.html.erb

app/views/stamps/_form.html.haml
= form_for @stamp do |f|
  - if @stamp.errors.any?
    #error_explanation
      %h2= "#{pluralize(@stamp.errors.count, "error")} prohibited this stamp from being saved:"
      %ul
        - @stamp.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :tournament_id
    = f.number_field :tournament_id
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :beacon_minor
    = f.number_field :beacon_minor
  .field
    = f.label :latitude
    = f.text_field :latitude
  .field
    = f.label :longitude
    = f.text_field :longitude
  .field
    = f.label :deleted
    = f.check_box :deleted
  .field
    = f.label :photo
    = f.file_field :photo
  .actions
    = f.submit 'Save'

app/views/stamps/edit.html.haml
%h1 Editing stamp

= render 'form'

= link_to 'Show', @stamp
\|
= link_to 'Back', stamps_path

app/views/stamps/index.html.haml
%h1 Listing stamps

%table
  %tr
    %th Tournament
    %th Name
    %th Beacon minor
    %th Latitude
    %th Longitude
    %th Deleted
    %th
    %th
    %th

  - @stamps.each do |stamp|
    %tr
      %td= stamp.tournament_id
      %td= stamp.name
      %td= stamp.beacon_minor
      %td= stamp.latitude
      %td= stamp.longitude
      %td= stamp.deleted
      %td= link_to 'Show', stamp
      %td= link_to 'Edit', edit_stamp_path(stamp)
      %td= link_to 'Destroy', stamp, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Stamp', new_stamp_path

app/views/stamps/new.html.haml
%h1 New stamp

= render 'form'

= link_to 'Back', stamps_path

app/views/stamps/show.html.haml
%p#notice= notice

%p
  %b Tournament:
  = @stamp.tournament_id
%p
  %b Name:
  = @stamp.name
%p
  %b Beacon minor:
  = @stamp.beacon_minor
%p
  %b Latitude:
  = @stamp.latitude
%p
  %b Longitude:
  = @stamp.longitude
%p
  %b Deleted:
  = @stamp.deleted
%p
  %b Photo:
  = image_tag @stamp.photo.url(:medium)

= link_to 'Edit', edit_stamp_path(@stamp)
\|
= link_to 'Back', stamps_path

app/views/tournaments/_form.html.haml
= form_for @tournament do |f|
  - if @tournament.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tournament.errors.count, "error")} prohibited this tournament from being saved:"
      %ul
        - @tournament.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :beacon_major
    = f.number_field :beacon_major
  .field
    = f.label :started_at
    = f.datetime_select :started_at
  .field
    = f.label :ended_at
    = f.datetime_select :ended_at
  .field
    = f.label :deleted
    = f.check_box :deleted
  .actions
    = f.submit 'Save'

app/views/tournaments/edit.html.haml
%h1 Editing tournament

= render 'form'

= link_to 'Show', @tournament
\|
= link_to 'Back', tournaments_path

app/views/tournaments/index.html.haml
%h1 Listing tournaments

%table
  %tr
    %th Name
    %th Beacon major
    %th Started at
    %th Ended at
    %th Deleted
    %th
    %th
    %th

  - @tournaments.each do |tournament|
    %tr
      %td= tournament.name
      %td= tournament.beacon_major
      %td= tournament.started_at
      %td= tournament.ended_at
      %td= tournament.deleted
      %td= link_to 'Show', tournament
      %td= link_to 'Edit', edit_tournament_path(tournament)
      %td= link_to 'Destroy', tournament, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Tournament', new_tournament_path

app/views/tournaments/new.html.haml
%h1 New tournament

= render 'form'

= link_to 'Back', tournaments_path

app/views/tournaments/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @tournament.name
%p
  %b Beacon major:
  = @tournament.beacon_major
%p
  %b Started at:
  = @tournament.started_at
%p
  %b Ended at:
  = @tournament.ended_at
%p
  %b Deleted:
  = @tournament.deleted

= link_to 'Edit', edit_tournament_path(@tournament)
\|
= link_to 'Back', tournaments_path